/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fortytwo.app;


import fortytwo.model.*;
import fortytwo.controller.*;


public class App {
    public static void main(String[] args) {
        GameController gc = new GameController();
        Game game = gc.createGame();
        gc.playGame(game);
    }
}
